CREATE TABLE Players (
    name VARCHAR(64) PRIMARY KEY,
    crypt CHAR(64) UNIQUE NOT NULL,
    wins INTEGER,
    losses INTEGER
);

CREATE TABLE Boards (
    player VARCHAR(64),
    slot INTEGER NOT NULL,
    game_id INTEGER,
    PRIMARY KEY (player, slot)
);

CREATE TABLE Games (
    game_id INTEGER PRIMARY KEY,
    white VARCHAR(64) NOT NULL,
    black VARCHAR(64) NOT NULL,
    s0 INTEGER, s1 INTEGER, s2 INTEGER, s3 INTEGER,
    s4 INTEGER, s5 INTEGER, s6 INTEGER, s7 INTEGER,
    s8 INTEGER, s9 INTEGER, s10 INTEGER, s11 INTEGER,
    s12 INTEGER, s13 INTEGER, s14 INTEGER, s15 INTEGER,
    s16 INTEGER, s17 INTEGER, s18 INTEGER, s19 INTEGER,
    s20 INTEGER, s21 INTEGER, s22 INTEGER, s23 INTEGER,
    s24 INTEGER, s25 INTEGER, s26 INTEGER, s27 INTEGER,
    s28 INTEGER, s29 INTEGER, s30 INTEGER, s31 INTEGER,
    s32 INTEGER, s33 INTEGER, s34 INTEGER, s35 INTEGER,
    s36 INTEGER, s37 INTEGER, s38 INTEGER, s39 INTEGER,
    s40 INTEGER, s41 INTEGER, s42 INTEGER, s43 INTEGER,
    s44 INTEGER, s45 INTEGER, s46 INTEGER, s47 INTEGER,
    s48 INTEGER, s49 INTEGER, s50 INTEGER, s51 INTEGER,
    s52 INTEGER, s53 INTEGER, s54 INTEGER, s55 INTEGER,
    s56 INTEGER, s57 INTEGER, s58 INTEGER, s59 INTEGER,
    s60 INTEGER, s61 INTEGER, s62 INTEGER, s63 INTEGER
);

CREATE TABLE Pieces (
    id INTEGER PRIMARY KEY,
    kind INTEGER,
    owner VARCHAR(64),
    takes INTEGER
);
