// Copyright 2017 Matthew Juran
// All Rights Reserved

package wichessing

import ()

var CastlingMovesCases = []AvailableMovesCase{
	{
		Name:      "Computer Game: No Castle Because Of Check",
		Active:    Black,
		Check:     true,
		Checkmate: true,
		Position: PointSet{
			&WhiteKingStart:      {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
			&BlackPawn1Start:     {},
			&BlackPawn2Start:     {},
			&BlackPawn3Start:     {},
			&BlackPawn4Start:     {},
			&BlackPawn5Start:     {},
			&BlackPawn6Start:     {},
			&BlackPawn7Start:     {},
			{
				AbsPoint: AbsPoint{0, 7},
				Piece: &Piece{
					Kind:        Rook,
					Orientation: White,
					Moved:       true,
				},
			}: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves:        map[AbsPoint]AbsPointSet{},
	},
	{
		Name:      "Random Testing: No Castle, In Check",
		Active:    Black,
		Check:     true,
		Checkmate: true,
		Position: PointSet{
			{
				AbsPoint: AbsPoint{6, 1},
				Piece: &Piece{
					Kind:        King,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{0, 2},
				Piece: &Piece{
					Kind:        GuardRook,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{4, 2},
				Piece: &Piece{
					Kind:        Queen,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{5, 3},
				Piece: &Piece{
					Kind:        Bishop,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{6, 3},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{3, 4},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{5, 5},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{7, 6},
				Piece: &Piece{
					Kind:        Rook,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{2, 7},
				Piece: &Piece{
					Kind:        Rook,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 2},
		Moves:        map[AbsPoint]AbsPointSet{},
	},
	{
		Name:      "Computer Didn't Castle",
		Active:    Black,
		Check:     true,
		Checkmate: true,
		Position: PointSet{
			{
				AbsPoint: AbsPoint{0, 0},
				Piece: &Piece{
					Kind:        Bishop,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			&WhiteLeftKnightStart:  {},
			&WhiteRightKnightStart: {},
			&WhiteRightRookStart:   {},
			&WhitePawn0Start:       {},
			&WhitePawn6Start:       {},
			&WhitePawn7Start:       {},
			{
				AbsPoint: AbsPoint{3, 2},
				Piece: &Piece{
					Kind:        King,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{0, 5},
				Piece: &Piece{
					Kind:        Bishop,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{1, 5},
				Piece: &Piece{
					Kind:        Bishop,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{6, 5},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			&BlackPawn3Start: {},
			&BlackPawn4Start: {},
			&BlackPawn5Start: {},
			&BlackPawn7Start: {},
			{
				AbsPoint: AbsPoint{3, 7},
				Piece: &Piece{
					Kind:        Queen,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{1, 0}: {
				{0, 2}: {},
				{2, 2}: {},
				{3, 1}: {},
			},
			{6, 0}: {
				{4, 1}: {},
				{5, 2}: {},
				{7, 2}: {},
			},
			{0, 1}: {
				{0, 2}: {},
				{0, 3}: {},
			},
			{6, 1}: {
				{6, 2}: {},
				{6, 3}: {},
			},
			{7, 1}: {
				{7, 2}: {},
				{7, 3}: {},
			},
			{3, 2}: {
				{2, 1}: {},
				{3, 1}: {},
				{4, 1}: {},
				{4, 2}: {},
				{4, 3}: {},
				{2, 3}: {},
			},
			{0, 5}: {
				{1, 4}: {},
				{2, 3}: {},
				{1, 6}: {},
				{2, 7}: {},
			},
			{1, 5}: {
				{0, 6}: {},
				{2, 6}: {},
				{0, 4}: {},
				{2, 4}: {},
				{3, 3}: {},
				{4, 2}: {},
				{5, 1}: {},
			},
			{3, 7}: {
				{2, 7}: {},
				{1, 7}: {},
				{0, 7}: {},
				{2, 6}: {},
				{3, 6}: {},
				{4, 6}: {},
				{4, 7}: {},
			},
			{4, 7}: {
				{6, 7}: {},
			},
		},
	},
	{
		Name:   "White Castling Moves Blocked",
		Active: White,
		Position: PointSet{
			&WhiteLeftRookStart:    {},
			&WhiteLeftBishopStart:  {},
			&WhiteKingStart:        {},
			&WhiteRightBishopStart: {},
			&WhiteRightRookStart:   {},
			&BlackLeftRookStart:    {},
			&BlackKingStart:        {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
			},
			{2, 0}: {
				{1, 1}: {},
				{0, 2}: {},
				{3, 1}: {},
				{4, 2}: {},
				{5, 3}: {},
				{6, 4}: {},
				{7, 5}: {},
			},
			{4, 0}: {
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
			},
			{5, 0}: {
				{4, 1}: {},
				{3, 2}: {},
				{2, 3}: {},
				{1, 4}: {},
				{0, 5}: {},
				{6, 1}: {},
				{7, 2}: {},
			},
			{7, 0}: {
				{6, 0}: {},
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
			},
			{0, 7}: {
				{3, 7}: {},
				{2, 7}: {},
				{1, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{4, 7}: {
				{3, 7}: {},
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{5, 7}: {},
				{2, 7}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{5, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
		},
	},
	{
		Name:   "Black Castling Moves Blocked",
		Active: Black,
		Position: PointSet{
			&WhiteLeftRookStart:    {},
			&WhiteKingStart:        {},
			&WhiteRightRookStart:   {},
			&BlackLeftRookStart:    {},
			&BlackLeftBishopStart:  {},
			&BlackKingStart:        {},
			&BlackRightBishopStart: {},
			&BlackRightRookStart:   {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{2, 0}: {},
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
				{6, 0}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{0, 7}: {
				{1, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{2, 7}: {
				{1, 6}: {},
				{0, 5}: {},
				{3, 6}: {},
				{4, 5}: {},
				{5, 4}: {},
				{6, 3}: {},
				{7, 2}: {},
			},
			{4, 7}: {
				{3, 7}: {},
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
			},
			{5, 7}: {
				{4, 6}: {},
				{3, 5}: {},
				{2, 4}: {},
				{1, 3}: {},
				{0, 2}: {},
				{6, 6}: {},
				{7, 5}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
		},
	},
	{
		Name:   "No Right Black Castling Move, King Movement Threatened",
		Active: Black,
		Position: PointSet{
			&WhiteLeftRookStart:  {},
			&WhiteKingStart:      {},
			&WhiteRightRookStart: {},
			&BlackLeftRookStart:  {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
			&Point{
				AbsPoint: AbsPoint{6, 6},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: White,
					Moved:       true,
				},
			}: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{2, 0}: {},
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
				{6, 0}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{0, 7}: {
				{1, 7}: {},
				{2, 7}: {},
				{3, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{4, 7}: {
				{2, 7}: {},
				{3, 7}: {},
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{5, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
			{6, 6}: {
				{7, 7}: {},
				{6, 7}: {},
			},
		},
	},
	{
		Name:   "No Left Black Castling Move, King Movement Threatened",
		Active: Black,
		Position: PointSet{
			&WhiteLeftRookStart:  {},
			&WhiteKingStart:      {},
			&WhiteRightRookStart: {},
			&BlackLeftRookStart:  {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
			&Point{
				AbsPoint: AbsPoint{2, 6},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: White,
					Moved:       true,
				},
			}: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{2, 0}: {},
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
				{6, 0}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{0, 7}: {
				{1, 7}: {},
				{2, 7}: {},
				{3, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{4, 7}: {
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{6, 7}: {},
				{5, 7}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{5, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
			{2, 6}: {
				{2, 7}: {},
			},
		},
	},
	{
		Name:   "No Right White Castling Move, King Movement Threatened",
		Active: White,
		Position: PointSet{
			&WhiteLeftRookStart:  {},
			&WhiteKingStart:      {},
			&WhiteRightRookStart: {},
			&BlackLeftRookStart:  {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
			&Point{
				AbsPoint: AbsPoint{6, 1},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{2, 0}: {},
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{0, 7}: {
				{1, 7}: {},
				{2, 7}: {},
				{3, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{4, 7}: {
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{2, 7}: {},
				{6, 7}: {},
				{5, 7}: {},
				{3, 7}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{5, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
			{6, 1}: {
				{6, 0}: {},
				{7, 0}: {},
			},
		},
	},
	{
		Name:   "No Left White Castling Move, King Movement Threatened",
		Active: White,
		Position: PointSet{
			&WhiteLeftRookStart:  {},
			&WhiteKingStart:      {},
			&WhiteRightRookStart: {},
			&BlackLeftRookStart:  {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
			&Point{
				AbsPoint: AbsPoint{2, 1},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
				{6, 0}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{0, 7}: {
				{1, 7}: {},
				{2, 7}: {},
				{3, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{4, 7}: {
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{2, 7}: {},
				{6, 7}: {},
				{5, 7}: {},
				{3, 7}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{5, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
			{2, 1}: {
				{2, 0}: {},
			},
		},
	},
	{
		Name:   "No Castling Moves, King Movement Threatened",
		Active: White,
		Position: PointSet{
			&WhiteLeftRookStart:  {},
			&WhiteKingStart:      {},
			&WhiteRightRookStart: {},
			&BlackLeftRookStart:  {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
			&Point{
				AbsPoint: AbsPoint{2, 1},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			&Point{
				AbsPoint: AbsPoint{6, 1},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			&Point{
				AbsPoint: AbsPoint{2, 6},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			&Point{
				AbsPoint: AbsPoint{6, 6},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: White,
					Moved:       true,
				},
			}: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{0, 7}: {
				{1, 7}: {},
				{2, 7}: {},
				{3, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{4, 7}: {
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{5, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
			{2, 1}: {
				{2, 0}: {},
			},
			{6, 1}: {
				{6, 0}: {},
				{7, 0}: {},
			},
			{2, 6}: {
				{2, 7}: {},
			},
			{6, 6}: {
				{6, 7}: {},
				{7, 7}: {},
			},
		},
	},
	{
		Name:   "All Left Castling Moves, Rook Skip Squares Threatened",
		Active: Black,
		Position: PointSet{
			&WhiteLeftRookStart:  {},
			&WhiteKingStart:      {},
			&WhiteRightRookStart: {},
			&BlackLeftRookStart:  {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
			&Point{
				AbsPoint: AbsPoint{0, 1},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			&Point{
				AbsPoint: AbsPoint{7, 1},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			&Point{
				AbsPoint: AbsPoint{0, 6},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			&Point{
				AbsPoint: AbsPoint{7, 6},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: White,
					Moved:       true,
				},
			}: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
				{2, 0}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{0, 7}: {
				{0, 6}: {},
				{1, 7}: {},
				{2, 7}: {},
				{3, 7}: {},
			},
			{4, 7}: {
				{3, 7}: {},
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{5, 7}: {},
				{2, 7}: {},
			},
			{7, 7}: {
				{7, 6}: {},
				{6, 7}: {},
				{5, 7}: {},
			},
		},
	},
	{
		Name:   "No Black Castling Moves, Black King Checked",
		Active: Black,
		Check:  true,
		Position: PointSet{
			&WhiteLeftRookStart:  {},
			&WhiteKingStart:      {},
			&WhiteRightRookStart: {},
			&BlackLeftRookStart:  {},
			&Point{
				AbsPoint: AbsPoint{3, 6},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
				{2, 0}: {},
				{6, 0}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{3, 6}: {
				{3, 7}: {},
				{4, 7}: {},
			},
			{4, 7}: {
				{3, 7}: {},
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{5, 7}: {},
			},
		},
	},
	{
		Name:   "No White Castling Moves, White King Checked",
		Active: White,
		Check:  true,
		Position: PointSet{
			&WhiteLeftRookStart: {},
			&Point{
				AbsPoint: AbsPoint{3, 1},
				Piece: &Piece{
					Kind:        Pawn,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			&WhiteKingStart:      {},
			&WhiteRightRookStart: {},
			&BlackLeftRookStart:  {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{4, 0}: {
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
			},
			{3, 1}: {
				{3, 0}: {},
				{4, 0}: {},
			},
			{0, 7}: {
				{1, 7}: {},
				{2, 7}: {},
				{3, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{4, 7}: {
				{3, 7}: {},
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{5, 7}: {},
				{2, 7}: {},
				{6, 7}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{5, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
		},
	},
	{
		Name:   "No Castling Moves, Rooks Moved",
		Active: Black,
		Position: PointSet{
			{
				AbsPoint: AbsPoint{0, 0},
				Piece: &Piece{
					Kind:        Rook,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			&WhiteKingStart: {},
			{
				AbsPoint: AbsPoint{7, 0},
				Piece: &Piece{
					Kind:        Rook,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{0, 7},
				Piece: &Piece{
					Kind:        Rook,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{4, 7},
				Piece: &Piece{
					Kind:        King,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			{
				AbsPoint: AbsPoint{7, 7},
				Piece: &Piece{
					Kind:        Rook,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{0, 7}: {
				{1, 7}: {},
				{2, 7}: {},
				{3, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{4, 7}: {
				{3, 7}: {},
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{5, 7}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{5, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
		},
	},
	{
		Name:   "No Castling Moves, King Moved",
		Active: Black,
		Position: PointSet{
			&WhiteLeftRookStart: {},
			{
				AbsPoint: AbsPoint{4, 0},
				Piece: &Piece{
					Kind:        King,
					Orientation: White,
					Moved:       true,
				},
			}: {},
			&WhiteRightRookStart: {},
			&BlackLeftRookStart:  {},
			{
				AbsPoint: AbsPoint{4, 7},
				Piece: &Piece{
					Kind:        King,
					Orientation: Black,
					Moved:       true,
				},
			}: {},
			&BlackRightRookStart: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{0, 7}: {
				{1, 7}: {},
				{2, 7}: {},
				{3, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{4, 7}: {
				{3, 7}: {},
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{5, 7}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{5, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
		},
	},
	{
		Name:   "All Castling Moves",
		Active: White,
		Position: PointSet{
			&WhiteLeftRookStart:  {},
			&WhiteKingStart:      {},
			&WhiteRightRookStart: {},
			&BlackLeftRookStart:  {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
				{2, 0}: {},
				{6, 0}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{0, 7}: {
				{1, 7}: {},
				{2, 7}: {},
				{3, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{4, 7}: {
				{3, 7}: {},
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{5, 7}: {},
				{2, 7}: {},
				{6, 7}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{5, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
		},
	},
	{
		Name:   "Castling Moves, No Left Rook",
		Active: White,
		Position: PointSet{
			&WhiteKingStart:      {},
			&WhiteRightRookStart: {},
			&BlackKingStart:      {},
			&BlackRightRookStart: {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{4, 0}: {
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
				{6, 0}: {},
			},
			{7, 0}: {
				{7, 1}: {},
				{7, 2}: {},
				{7, 3}: {},
				{7, 4}: {},
				{7, 5}: {},
				{7, 6}: {},
				{7, 7}: {},
				{6, 0}: {},
				{5, 0}: {},
			},
			{4, 7}: {
				{3, 7}: {},
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{5, 7}: {},
				{6, 7}: {},
			},
			{7, 7}: {
				{6, 7}: {},
				{5, 7}: {},
				{7, 6}: {},
				{7, 5}: {},
				{7, 4}: {},
				{7, 3}: {},
				{7, 2}: {},
				{7, 1}: {},
				{7, 0}: {},
			},
		},
	},
	{
		Name:   "Castling Moves, No Right Rook",
		Active: White,
		Position: PointSet{
			&WhiteLeftRookStart: {},
			&WhiteKingStart:     {},
			&BlackLeftRookStart: {},
			&BlackKingStart:     {},
		},
		PreviousFrom: AbsPoint{3, 3},
		PreviousTo:   AbsPoint{3, 4},
		Moves: map[AbsPoint]AbsPointSet{
			{0, 0}: {
				{0, 1}: {},
				{0, 2}: {},
				{0, 3}: {},
				{0, 4}: {},
				{0, 5}: {},
				{0, 6}: {},
				{0, 7}: {},
				{1, 0}: {},
				{2, 0}: {},
				{3, 0}: {},
			},
			{4, 0}: {
				{3, 0}: {},
				{3, 1}: {},
				{4, 1}: {},
				{5, 1}: {},
				{5, 0}: {},
				{2, 0}: {},
			},
			{0, 7}: {
				{1, 7}: {},
				{2, 7}: {},
				{3, 7}: {},
				{0, 6}: {},
				{0, 5}: {},
				{0, 4}: {},
				{0, 3}: {},
				{0, 2}: {},
				{0, 1}: {},
				{0, 0}: {},
			},
			{4, 7}: {
				{3, 7}: {},
				{3, 6}: {},
				{4, 6}: {},
				{5, 6}: {},
				{5, 7}: {},
				{2, 7}: {},
			},
		},
	},
}
